import { useEffect, type RefObject } from 'react'

/**
 * INTERACTION LAYER
 * -----------------------------------------------------------------------------
 * Applies the interaction system to the generated Figma design *from the
 * outside*, by tagging elements with data-ix roles that interaction-system.css
 * then styles.
 *
 * Why it works this way:
 *   src/imports/Homepage/index.tsx is generated by Figma Make and is the
 *   canonical source of truth. Re-exporting from Figma overwrites it. Keeping
 *   the interaction layer external means design updates can be dropped in
 *   without losing any of this behaviour, and the design file stays
 *   byte-identical to the export.
 *
 * Elements are located structurally (by data-name, by the Tailwind classes the
 * export emits, and by text content) rather than by DOM index, so small design
 * changes don't silently break the layer.
 *
 * Roles: link | pill | button | icon | card | field | fab
 */

type Role = 'link' | 'pill' | 'button' | 'icon' | 'card' | 'field' | 'fab'

/** Marks an element with a role, and makes it keyboard-operable. */
function assign(el: Element | null | undefined, role: Role, label?: string): void {
  if (!el || !(el instanceof HTMLElement)) return
  if (el.dataset.ix) return // already tagged — keeps re-runs idempotent

  // Some links (the footer's legal row) are underlined in the design itself.
  // This must be read BEFORE tagging, otherwise the interaction layer's own
  // underline rule is already in effect and the check reads its own output.
  // Those links keep the design's underline and use the lift alone on hover.
  if (role === 'link') {
    const label = el.querySelector('p')
    const decorated =
      label && getComputedStyle(label).textDecorationLine.includes('underline')
    if (decorated) el.dataset.ixUnderlined = ''
  }

  el.dataset.ix = role

  // Native <button> elements already do all of this for themselves.
  if (el.tagName !== 'BUTTON' && el.tagName !== 'INPUT') {
    el.setAttribute('role', role === 'link' ? 'link' : 'button')
    el.setAttribute('tabindex', '0')
    if (label) el.setAttribute('aria-label', label)

    // Keyboard parity: Enter/Space should activate, exactly like a real button.
    el.addEventListener('keydown', (event) => {
      const key = (event as KeyboardEvent).key
      if (key !== 'Enter' && key !== ' ') return
      event.preventDefault()
      el.click()
    })
  }
}

/** querySelectorAll that matches on a fragment of the class attribute. */
function byClass(root: ParentNode, fragment: string): HTMLElement[] {
  return Array.from(root.querySelectorAll<HTMLElement>(`[class*="${fragment}"]`))
}

/** Nearest ancestor whose class attribute contains `fragment`. */
function closestByClass(el: Element, fragment: string, stopAt: Element): HTMLElement | null {
  let node: Element | null = el.parentElement
  while (node && node !== stopAt) {
    if (node instanceof HTMLElement && node.className.includes(fragment)) return node
    node = node.parentElement
  }
  return null
}

/** Finds elements whose entire trimmed text equals one of `labels`. */
function byText(root: ParentNode, selector: string, labels: string[]): HTMLElement[] {
  return Array.from(root.querySelectorAll<HTMLElement>(selector)).filter((el) =>
    labels.includes((el.textContent || '').trim()),
  )
}

/* -------------------------------------------------------------------------- */
/* Header                                                                      */
/* -------------------------------------------------------------------------- */

function tagHeader(root: HTMLElement): void {
  // Container6's inner row: [ logo, nav, icons ]
  const row = byClass(root, 'gap-[281px]')[0]
  if (!row) return

  const [logo, nav, icons] = Array.from(row.children)

  assign(logo, 'icon', 'Curio — home')
  if (logo instanceof HTMLElement) logo.dataset.ixSize = 'lg'

  // Nav: About / Catalog / Blog / Contact live inside the gap-[88px] row.
  const navRow = nav ? byClass(nav, 'gap-[88px]')[0] : null
  if (navRow) {
    Array.from(navRow.children).forEach((item) => {
      const label = (item.textContent || '').trim()
      assign(item, 'link', label)
    })
  }

  // Icons: [ search, cart, cart-badge ]
  if (icons) {
    const [search, cart, badge] = Array.from(icons.children)
    assign(search, 'icon', 'Search')
    assign(cart, 'icon', 'Cart')
    if (badge instanceof HTMLElement) badge.dataset.ixBadge = ''
  }
}

/* -------------------------------------------------------------------------- */
/* Pills — age groups, skill categories, and "Add"                             */
/* -------------------------------------------------------------------------- */

function tagPills(root: HTMLElement): void {
  // Age pills (2-4, 5-6, 7-8, 9-10) and category pills (Fine Motor, STEM,
  // Logic, Creativity, Focus, Problem Solving) share the rounded-[20px] shape.
  // The image tiles reuse that radius, so require a direct <p> child to
  // distinguish a real pill from a picture.
  byClass(root, 'rounded-[20px]').forEach((el) => {
    const hasDirectLabel = Array.from(el.children).some((child) => child.tagName === 'P')
    if (!hasDirectLabel) return
    assign(el, 'pill', (el.textContent || '').trim())
  })

  // "Add" buttons on the product cards.
  root.querySelectorAll<HTMLElement>('[data-name="button"]').forEach((el) => {
    assign(el, 'pill', 'Add to cart')
  })

  // Wishlist hearts sit next to each Add button.
  root.querySelectorAll<HTMLElement>('[data-name="Vector"]').forEach((el) => {
    const isHeartSized = el.className.includes('w-[34px]') && el.className.includes('h-[30px]')
    if (isHeartSized) assign(el, 'icon', 'Add to wishlist')
  })
}

/* -------------------------------------------------------------------------- */
/* Filled CTAs — Shop Now, Subscribe, View all                                 */
/* -------------------------------------------------------------------------- */

function tagButtons(root: HTMLElement): void {
  // Shop Now — the hero CTA (w-[181px] pill).
  byClass(root, 'w-[181px]').forEach((el) => assign(el, 'button', 'Shop Now'))

  // Subscribe — the newsletter CTA (w-[129px] pill).
  byClass(root, 'w-[129px]').forEach((el) => assign(el, 'button', 'Subscribe'))

  // "View all" — text + arrow, so it reads as a link with a nudging arrow.
  byText(root, '[data-name="Button"]', ['View all']).forEach((el) => {
    assign(el, 'link', 'View all')
    const arrow = el.querySelector<HTMLElement>('[data-name="ArrowRight"]')
    if (arrow) arrow.dataset.ixArrow = ''
  })
}

/* -------------------------------------------------------------------------- */
/* Cards — product, age and category tiles                                     */
/* -------------------------------------------------------------------------- */

function tagCards(root: HTMLElement): void {
  const cards = new Set<HTMLElement>()

  // A card is the block that pairs artwork with a pill. The three card kinds
  // wrap differently — product cards carry rounded-[10px] and w-[250px], age
  // cards carry only rounded-[10px], category cards carry neither — so the
  // reliable signal is "nearest ancestor holding both an image and this pill".
  root.querySelectorAll<HTMLElement>('[data-ix="pill"]').forEach((pill) => {
    // Prefer the design's own card shape when there is one...
    let node: Element | null = pill.parentElement
    let fallback: HTMLElement | null = null

    while (node && node !== root) {
      if (node instanceof HTMLElement && node.querySelector('img')) {
        if (node.className.includes('rounded-[10px]')) {
          cards.add(node)
          return
        }
        // ...otherwise remember the first image-bearing ancestor (categories).
        if (!fallback) fallback = node
      }
      node = node.parentElement
    }

    if (fallback) cards.add(fallback)
  })

  cards.forEach((card) => {
    assign(card, 'card')

    // Cards without a radius of their own get lift without shadow.
    if (!card.className.includes('rounded-')) card.dataset.ixFlat = ''

    // Let the artwork push in slightly behind the card lift.
    card.querySelectorAll('img').forEach((img) => {
      const holder = img.parentElement
      if (holder instanceof HTMLElement) holder.dataset.ixMedia = ''
    })
  })
}

/* -------------------------------------------------------------------------- */
/* Footer                                                                      */
/* -------------------------------------------------------------------------- */

function tagFooter(root: HTMLElement): void {
  root.querySelectorAll<HTMLElement>('[data-name="li"], [data-name="a"]').forEach((el) => {
    assign(el, 'link', (el.textContent || '').trim())
  })
}

/* -------------------------------------------------------------------------- */
/* Newsletter email field — swap the static <p> for a real <input>             */
/* -------------------------------------------------------------------------- */

const PLACEHOLDER = 'your.mail.here@gmail.com'

function mountEmailInput(root: HTMLElement): void {
  const field = root.querySelector<HTMLElement>('[data-name="input"]')
  if (!field || field.dataset.ixField === 'mounted') return

  const label = Array.from(field.querySelectorAll('p')).find(
    (p) => (p.textContent || '').trim() === PLACEHOLDER,
  )
  if (!label) return

  const input = document.createElement('input')
  input.type = 'email'
  input.placeholder = PLACEHOLDER
  input.setAttribute('aria-label', 'Email address')
  input.autocomplete = 'email'

  // Inheriting the <p>'s classes keeps font, size, weight and colour identical
  // to the design; .ix-input only strips the browser's default chrome.
  input.className = `${label.className} ix-input`

  label.replaceWith(input)

  field.dataset.ixField = 'mounted'
  field.dataset.ix = 'field'
}

/* -------------------------------------------------------------------------- */
/* Floating AI agent                                                           */
/* -------------------------------------------------------------------------- */

function tagFab(root: HTMLElement): void {
  const fab = root.querySelector<HTMLElement>('[data-name="AI Agent"]')
  assign(fab, 'fab', 'Ask the AI assistant')
}

/* -------------------------------------------------------------------------- */

function applyInteractionLayer(root: HTMLElement): void {
  tagHeader(root)
  tagPills(root)
  tagButtons(root)
  tagCards(root) // must run after tagPills — it locates cards via their pills
  tagFooter(root)
  mountEmailInput(root)
  tagFab(root)
}

/**
 * Applies the interaction layer to the subtree under `ref` once it is mounted,
 * and re-applies it if React ever replaces part of the tree.
 */
export function useInteractionLayer(ref: RefObject<HTMLElement | null>): void {
  useEffect(() => {
    const root = ref.current
    if (!root) return

    let observer: MutationObserver | null = null
    let queued = false

    const run = () => {
      queued = false
      observer?.disconnect() // don't observe our own mutations
      applyInteractionLayer(root)
      observer?.observe(root, { childList: true, subtree: true })
    }

    observer = new MutationObserver(() => {
      if (queued) return
      queued = true
      requestAnimationFrame(run)
    })

    run()

    return () => observer?.disconnect()
  }, [ref])
}
